apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: discord-webhook
  data:
    - secretKey: webhookUrl
      remoteRef:
        key: discord-webhook-url
