---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-platform-caferdg-io-v1alpha1-gitlabproject
  failurePolicy: Fail
  name: mgitlabproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - platform.caferdg.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gitlabprojects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-platform-caferdg-io-v1alpha1-notifier
  failurePolicy: Fail
  name: mnotifier-v1alpha1.kb.io
  rules:
  - apiGroups:
    - platform.caferdg.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notifiers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-platform-caferdg-io-v1alpha1-gitlabproject
  failurePolicy: Fail
  name: vgitlabproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - platform.caferdg.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gitlabprojects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-platform-caferdg-io-v1alpha1-notifier
  failurePolicy: Fail
  name: vnotifier-v1alpha1.kb.io
  rules:
  - apiGroups:
    - platform.caferdg.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notifiers
  sideEffects: None
