# This rule is not used by the project demo itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to platform.caferdg.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/managed-by: kustomize
  name: gitlabproject-viewer-role
rules:
- apiGroups:
  - platform.caferdg.io
  resources:
  - gitlabprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.caferdg.io
  resources:
  - gitlabprojects/status
  verbs:
  - get
