apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: YOUR-GCP-PROJECT-ID
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-key
            key: credentials.json
            namespace: external-secrets
